---
deployment:
  tasks:
    # ============================================
    # IMPORTANT: Update the DEPLOYPATH below!
    # Replace 'username' with your actual cPanel username
    # Common paths:
    # - Node.js app: /home/username/node_app/
    # - API subdirectory: /home/username/public_html/api/
    # - Custom path: /home/username/apps/ecommerce/
    # ============================================
    - export DEPLOYPATH=/home/username/public_html/api/
    
    # Create deployment directory if it doesn't exist
    - mkdir -p $DEPLOYPATH
    
    # Copy source files (exclude tests and mocks)
    - /bin/cp -R src/ $DEPLOYPATH
    
    # Copy Prisma files (schema and migrations) - Required for database
    - /bin/cp -R prisma/ $DEPLOYPATH
    
    # Copy essential configuration files
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp prisma.config.ts $DEPLOYPATH
    
    # Copy documentation (optional - remove if you don't want docs on server)
    - /bin/cp README.md $DEPLOYPATH 2>/dev/null || true
    - /bin/cp API_DOCUMENTATION.md $DEPLOYPATH 2>/dev/null || true
    - /bin/cp ADMIN_API_DOCUMENTATION.md $DEPLOYPATH 2>/dev/null || true
    
    # Navigate to deployment directory
    - cd $DEPLOYPATH
    
    # Install production dependencies only (excludes devDependencies like jest)
    - npm ci --production --silent
    
    # Generate Prisma Client (required for database queries)
    - npx prisma generate
    
    # IMPORTANT: Uncomment the line below to run migrations automatically
    # WARNING: Only enable after initial deployment and testing
    # This will apply all pending migrations on each deployment
    # - npx prisma migrate deploy
    
    # Set proper permissions on server file
    - chmod +x $DEPLOYPATH/src/server.js 2>/dev/null || true
    
    # Clean up any old node_modules/.cache if exists
    - rm -rf $DEPLOYPATH/node_modules/.cache 2>/dev/null || true
