// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import path from "path";
import fs from "fs";

// Trust environment variables first (Coolify), only load .env as a fallback for local dev
if (!process.env.DB_HOST) {
  const envPath = path.resolve(process.cwd(), '.env');
  if (fs.existsSync(envPath)) {
    config({ path: envPath });
  }
}
import { defineConfig } from "prisma/config";

const dbUser = process.env.DB_USER || 'root';
const dbPass = process.env.DB_PASSWORD || '';
const dbHost = process.env.DB_HOST || 'localhost';
const dbPort = process.env.DB_PORT || '3306';
const dbName = process.env.DB_NAME || '';

// Construct URL for Prisma CLI tools (migrations, etc.)
const databaseUrl = process.env.DATABASE_URL || `mysql://${dbUser}:${dbPass}@${dbHost}:${dbPort}/${dbName}`;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
